Fixed Syntax Errors
nodejs/website-redesign pull request #114
Opened 2018-11-23 18:02 UTC by VisibleMarkov

Fixed syntax errors in documents caused by the map function not have a closing bracket. 
Also fixed an incorrect comment.

2018-11-23 18:19 UTC, ghost requested changes

2018-11-23 18:19 UTC, flowkraD commented on documentation/0045-node-folders/index.md
> +})
This isn't right. The filter map closes after the path.join() function but the `}` definitely out of place.

2018-11-23 18:27 UTC, Kriyszig commented on documentation/0045-node-folders/index.md
> +})
Fixed in cec8a13.
Thanks a lot for pointing that out.

2018-11-23 18:33 UTC, ghost approved these changes
LGTM

2018-11-23 18:34 UTC, flowkraD commented
Thanks @VisibleMarkov for fixing this (^_^)

2018-11-24 04:07 UTC, flowkraD commented
@amiller-gh,
Can we land this now given these errors exist in master?

2018-11-24 13:36 UTC, ZanMarolt approved these changes
Nice catch

2018-11-25 17:43 UTC, amiller-gh commented
LGTM! Thanks for the catch!

2018-11-25 17:43 UTC, merged