Update README.md with Co-Champions
nodejs/website-redesign pull request #37
Opened 2018-04-18 18:45 UTC by chowdhurian

Update champions per private session discussion in last Website Redesign meeting (#30) and Olivia's move to CommComm Emeriti ([#290](https://github.com/nodejs/community-committee/pull/290)).

2018-04-18 18:50 UTC, ghost approved these changes

2018-04-18 18:55 UTC, maddhruv commented
How about putting your and Adam's name at the top! 😜

2018-04-21 21:00 UTC, pierreneter approved these changes

2018-04-21 21:17 UTC, milapbhojak commented
Hello Community,

Milap here, I am an engineer turned self taught designer with 3 years of experience. Also have been open source design contributor in PSF, Mozilla science labs, Airbnb Open source. I got to know about this project from [a post medium post](https://medium.com/the-node-js-collection/redesigning-nodejs-part-1-fac08a0e015a) by @amiller-gh  Very insightful post. Design needs lots of collaboration with users, stack holders and developers. Hence NodeJS is one of the largest open source project and redesigning their website would be very interesting journey with lots of new learnings. I would love to contribute in this project. Look forward to attend next meeting on 26th April meanwhile can i take a look on updated list of project requirements? Look forward to contribute :)

2018-04-23 20:26 UTC, chowdhurian commented
@milapbhojak we'd very much welcome your contributions. The Agenda subsection in [#38](https://github.com/nodejs/website-redesign/issues/38#issue-316783115) is what you're looking for. All the issues listed there make up the updated list of project requirements.

2018-04-24 22:56 UTC, amiller-gh commented
Glad to have you @milapbhojak! Look forward to meeting you in the next meeting 👍

2018-04-26 15:53 UTC, bnb approved these changes

2018-04-26 16:40 UTC, maddhruv commented on README.md
> +- [@milapbhojak] (https://github.com/milapbhojak) - **Milap Bhojak**
space is to be removed after `]`

2018-04-26 16:43 UTC, maddhruv requested changes

2018-04-26 16:43 UTC, maddhruv commented on README.md
> +Any person who wants to contribute to the initiative is welcome! Please read [CONTRIBUTING.md](https://github.com/nodejs/website-redesign/blob/update-members-and-champions/CONTRIBUTING.md) and join t
I guess the link for *CONTRIBUTING* file could be simply - `./CONTRIBUTING.md`

2018-04-27 07:48 UTC, chowdhurian commented
Thanks @maddhruv 🙏🏽

2018-04-28 00:32 UTC, maddhruv approved these changes

2018-04-28 00:32 UTC, merged